### ISSUE TITLE
Grid should re-center when user clicks-to-paste

### ISSUE THREAD

**Issue by gorf2000** [duppypro/does-it-glider#3]
If I click to paste and watch my life game play out, scrolling to follow,  and then if I click to paste again to see it from the beginning, the grid does not re-center to where the game starts
Repro on android with chrome browser

**Comment by gorf2000** [comment]
Or maybe have a recenter button, or a recenter on paste checkbox. Or also perhaps a restart button

**Comment by duppypro** [comment]
@gorf2000 I'm going to starts feature discussion in this issue because this is such a small project now.
Normally I would discourage discussing the spec in the issue comments, but this project isn't big enough for it's own Discord or Slack yet.

re-center on paste is definitely on the to-do list

I'm challenging myself in this project to have no or very few buttons and menus. I want it to just "do the right thing"

How quickly did you figure out that you could pan and zoom the grid? Do I need to add hints to that?

What do you think of a feature to automatically zoom and pan to a bounding box of the live_cells?
But if I do that, how do I respond to the user's pan and zoom interactions? Which takes precedence?
just asking this question made me think of one answer:
- Start auto zoom and pan mode when live cells leave the initial viewable window.
- When user manually zooms, pause auto fit mode.
- Resume auto fit mode after a few seconds of no user interaction

Another challenge is to figure out how to change speed without covering the screen with a slider.
One idea:
- Single tap pauses the animation
- subsequent single tap if enough delay restarts the animation at previous speed
- If the user taps twice (maybe thrice?) less than about 2 seconds apart, use the time delay between the taps to set the speed
 - the time between taps would by divided by 4 probably to set speed
 - should speed reset on paste? I'm thinking no
-

**Comment by duppypro** [comment]
Commit 3e11f2f fixed this
